[[redirects]]
  from = "https://setwithfriends.netlify.app/*"
  to = "https://setwithfriends.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/__/auth/*"
  to = "https://setwithfriends.web.app/__/auth/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
